config/routes.rb
Rails.application.routes.draw do

  root to: 'projects#index'

  resources :sessions, :only => [:destroy, :create, :new]
  
  resources :projects do #, :only =>[:new, :create, :index, :show] 
    resources :reviews, :only => [:index, :show, :create]
  end

  resources :pledges, :only =>[:create]

  resources :categories, :only =>[:index, :show]

  resources :users, :only =>[:new, :create, :show, :edit, :update]

  resources :user_sessions, :only=>[:new,:create, :destroy]
  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout


end

app/models/user.rb
class User < ActiveRecord::Base
has_secure_password

    
  has_many :projects
  has_many :rewards, :through => :projects
  has_many :pledges
  has_many :reviews

  #validates :username, :presence => true
  #validates :username, length: {minimum: 2}
  validates :email, :presence => true
  validates :email, :uniqueness => true

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "http://lorempixel.com/300/300/people/"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :ensure_logged_in, :only => [:show, :edit, :update]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to projects_path, notice: "Signed up!"
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to user_path(current_user.id), notice: 'your edits were saved'
    else
      render 'edit'
    end
  end

  private 

  def user_params
    params.require(:user).permit(:email, :biography, :phone, :username, :password, :avatar, :password_confirmation)
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="field">
  <%= f.label :password %>
  <%= f.password_field :password %>
</div>
<div class="field">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<div class="margin40"></div>


<div class="row">
	<div class="medium-6 columns">
		<h1>Edit Profile</h1>

		<%= form_for @user, :html => { :multipart => true } do |f| %>
			<div class="field">
				<%= f.label :username %>
				<%= f.text_field :username %>
			</div>
			<div class="field">
				<%= f.label :biography %>
				<%= f.text_area :biography %>
			</div>
			<div class="field">
				<%= f.label :phone %>
				<%= f.text_field :phone %>
			</div>
			<div class="field">
				<%= f.label :email %>
				<%= f.text_field :email %>
			</div>
			<div class="field">
				<%= f.label :avatar %>
				<%= f.file_field :avatar %>
			</div>
			<div class="action">
				<%= f.submit class: 'button small radius right', value: 'Save Changes' %>
			</div>
		<% end %>

	</div>
</div>

app/views/users/new.html.erb
<div class="row">
<div class="wrapper">
	<div class="medium-6 medium-centered columns padding_div">

		  <h3>Sign Up</h3>
			<%= form_for @user do |f| %>
			<% if @user.errors.any? %>
				<div data-alert class="alert-box alert radius">
  				<p>Form is invalid</p>
		      <ul>
		      <% for message in @user.errors.full_messages %>
		     <li class="alert-box-content">
		       <%= message %>
		     </li>
		        <% end %>
		      </ul>
  				<a href="#" class="close">&times;</a>
				</div>
			<% end %>  
				<div class="field">
					<%= f.label :email %>
					<%= f.text_field :email %>
				</div>
				<div class="field">
				  <%= f.label :password %>
				  <%= f.password_field :password %>
				</div>
				<div class="field">
				  <%= f.label :password_confirmation %>
				  <%= f.password_field :password_confirmation %>
				</div>
				<div class="actions">
					<%= submit_tag "Sign Up", class: 'button tiny success round right' %>
				</div>
		<% end %>	

		<div class="clearfix"></div>
	</div><!-- column -->
</div><!-- wrapper -->
</div><!-- row -->

app/views/users/show.html.erb
<div class="margin"></div>
<div class="row">

	<div class="medium-8 profile">

		<h1>My Profile</h1><hr>

		<div class="row">

				<div class="medium-6 columns">
					<ul class="no-bullet">
						<li><strong>Username:</strong> <%= @user.username %></li>
						<li><strong>Email:</strong> <%= @user.email %></li>
						<li><strong>Biography:</strong> <%= @user.biography %></li>
					</ul>
				</div>


				<div class="medium-6 columns"><br>

					 <%= link_to edit_user_path(@user.id) do  %>
						<button class='round'>Edit account</button>
					<% end %>
				</div>

		</div><hr>
	



		<div class="backed_projects">
			<table>
			  <thead>
				<tr>
					<th width="150">Project Name</th>
					<th width="80">Amount Pledged</th>
					<th width="500">Reward</th>
				</tr>
			  </thead>
				<% @user.pledges.each do |pledge| %>
					<tr> 
						<td><strong><%= pledge.reward.project.title %></strong></td>
						<td><%= pledge.reward.amount %></td>
						<td><%= pledge.reward.description %></td>
					</tr>
				<% end %>
			</table>
		</div>
		<br>
		<div class="owned_projects">
			<table>
				<thead>
				  <tr>
					<td width="150">Project Name</td>
					<td  width="80">Project Goal</td>
					<td width="500">Current Amount</td>
				  </tr>
			    </thead>
					<% @user.projects.each do |project| %>
						<tr>
							<td><%= link_to project.title, project_path(project.id) %></td>
							<td><%= project.goal %></td>
							<td><%= funding_count(project.rewards) %></td>
						</tr>
					<% end %>
				</tr>
			</table>
		</div>
 </div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>