config/routes.rb
Rails.application.routes.draw do

  root to: 'projects#index'

  resources :sessions, :only => [:destroy, :create, :new]
  
  resources :projects do #, :only =>[:new, :create, :index, :show] 
    resources :reviews, :only => [:index, :show, :create]
  end

  resources :pledges, :only =>[:create]

  resources :categories, :only =>[:index, :show]

  resources :users, :only =>[:new, :create, :show, :edit, :update]

  resources :user_sessions, :only=>[:new,:create, :destroy]
  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout


end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  has_many :rewards
  has_many :pledges, :through => :rewards
  has_many :reviews 
  has_many :users, :through => :reviews
  accepts_nested_attributes_for :rewards, :reject_if => :all_blank, :allow_destroy => true

  scope :most_recent_five, -> { all.limit(5) }

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "http://lorempixel.com/300/300/#{['technics','fashion','sports'].sample}/"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/


  validates :title, :start_time, :end_time, :description, :presence => true
  validates :title, length: {minimum: 3} 
  validates :description, length: {minimum: 4}

  validates :goal, numericality:{
  	greater_than: 0
  }


  validate :start_time_greater_than_6_hours_from_now
  validate :end_time_greater_than_2_days_from_start_time

  def get_backer_count_for_the_project
    rewards.inject(0){|sum,reward|
      num_backer_for_reward = reward.pledges.count
      sum + num_backer_for_reward
    }
  end

  def get_days_left
    if ((end_time.to_date - DateTime.now.to_date).to_i > 0)
      date_left = (end_time.to_date - DateTime.now.to_date).to_i
     " #{date_left} days left" 
    else
      "Expired"
    end
  end

  def is_expired?
    if ((end_time.to_date - DateTime.now.to_date).to_i > 0)
      false
    else
      true
    end
  end
  
  private
  
  def start_time_greater_than_6_hours_from_now
  	return if (start_time.nil?) 
  		if DateTime.now + 6.hour > start_time
  			errors.add(:start_time, "start time must be for at least 6 hours from now")
  		end
  end 

  def end_time_greater_than_2_days_from_start_time
  	return if (start_time.nil?) or (end_time.nil?)

  	if end_time - start_time < 2.days
  		errors.add(:end_time,"the end time is not 2 days greater than the start_time")
  	end



  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_filter :ensure_logged_in, except: [:index, :show]

  def index
  	@projects = if params[:search]
      Project.where("LOWER(title) LIKE LOWER(?)", "%#{params[:search]}%").order(created_at: :desc).page(params[:page])
      elsif params[:category_id]
        @category = Category.find(params[:category_id])
        @category.projects.order(created_at: :desc).page(params[:page])
      else
        Project.order('projects.created_at DESC').page(params[:page])
      end  

     @hash_amount_project = {}
     @projects.each{|project|
      @hash_amount_project[project.id] = calculate_sum_of_pledges(project)
     }

  	 @categories = Category.all
  	 @most_recent_project = Project.most_recent_five

     @total_money_raised = get_total_money_raised

    respond_to do |format|
      format.html
      format.js
    end


  end

  def new
    @project = Project.new
  end

  
  def show
    @rewards = @project.rewards
    puts "printing rewards" 
    @sum_of_amount = calculate_sum_of_pledges(@project)
    @current_user_amount_pledged = get_user_pledge_for_the_project
    @total_supporters = get_total_supporters
    if current_user
      @review = @project.reviews.build
    end
  end  

  def create
    @project = Project.new(project_params)
    @project.user = current_user
    respond_to do |format|
      if @project.save
        format.html { redirect_to  project_path(@project), notice: 'Project was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    def get_user_pledge_for_the_project
        all_pledges = @project.pledges
        all_pledges.each do |pledge|
           if pledge.user == current_user
              return pledge.reward.amount
           end
        end
        return 0
    end

    def get_total_supporters
      @project.pledges.count
    end 

    def calculate_sum_of_pledges(project)
        rewards = project.rewards
        sum_of_amount = rewards.inject(0) do |sum, reward|
            num_of_pledges = reward.pledges.count
            sum_of_the_reward = num_of_pledges * reward.amount
            sum + sum_of_the_reward
        end
    end


    # Never trust parameters from the scary internet, only allow the white list through.
  

    def project_params
      params.require(:project).permit(:title, :description, :goal, :start_time, :end_time, :image, :category_id, rewards_attributes: [:amount, :description, :_destroy])
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for @project, :html => { :multipart => true } do |f| %>
  <% if @project.errors.any? %>
    <div data-alert class="alert-box alert radius">
      <p><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</p>
      <ul>
        <% @project.errors.full_messages.each do |msg|%>
          <li class="alert-box-content"><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %>
    <br/>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :goal %>
    <br/>
    <%= f.number_field :goal %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <br/>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :start_time %>
    <br/>
    <%= f.date_field :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %>
    <br/>
    <%= f.date_field :end_time %>
  </div>
  <div class="field">
    <%= f.label :image %>
    <br/>
    <%= f.file_field :image %>
  </div>
    <div class="field">
    <%= f.label "Category" %>
    <%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]}, {}, :multiple => false %>
  </div><hr>

  <div id="rewards">
    <%= f.fields_for :rewards do |reward| %>
      <%= render 'reward_fields', :f => reward %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'Add Reward', f, :rewards, class: 'button tiny radius expand' %>
    </div>
  </div>
  <%= f.submit class: 'button success small radius right', value: 'Create Project' %><br><hr>
<% end %>

app/views/projects/_project.html.erb
    <li>
    <div class="th img">


    	<%= link_to image_tag(project.image.url(:medium)), project_path(project)%>

        <div class="overlay">
           
            <a href="<%= project_path(project)%>" class="expanded">Learn<span> more</span></a>

            <a href="<%= project_path(project)%>" class="anchor"></span></a>
            <a class="close-overlay hidden">x</a>
        </div>


        <p>
            <span class="title">project: <strong><%= project.title %></strong></span><span class="text-left days"><hr><%= project.get_days_left %></span><span class="right fund_raised" id="value" data-attribute-amount=<%= @hash_amount_project[project.id] %>>Fund raised: $<%= @hash_amount_project[project.id] %>
            </span>
            <span class="goal" style="display:none" data-attribute-goal=<%= project.goal  %>><%= project.goal %></span>
            <!-- <span> backers of the project: <%= project.get_backer_count_for_the_project%> </span> -->
        </p>

       <div class="progress round">
      	 	<span class="meter thumb_meter" style="width: 1%"></span>
    	</div>

    </div>

    </li>

app/views/projects/_review.html.erb
    <h3>Reviews</h3>

  <p>Reviews for <%= @project.title %></p>

  <% @project.reviews.each do |review| %>
    <p>
      <%= review.comment %>
      <br>
      <% if review.user != nil %>
        <em> by <%= review.user.email %></em>
        Added on: <%= review.created_at %>
      <% end %>
    </p>
  <% end %>
  </div>
  <% if current_user %>
  <div>
      <h4>New Review</h4>

  <%= form_for([@project, @review]) do |f| %>

    <div class="field">
      <%= f.label :comment %><br />
      <%= f.text_area :comment %>
    </div>
    <div class="actions">
      <%= f.submit "Submit Comment", :id => "review_submit"%>
    </div>
  <% end %>


  </div>

  <% else %>
    <p>Please <%= link_to "login", new_session_path %> to add a review</p>
  <% end %>

app/views/projects/_reward_fields.html.erb
<div>
  <%= f.label :amount %>
  <%= f.text_field :amount %>
</div>

<div>
  <%= f.label :description %>
  <%= f.text_field :description %>
</div>

<%= link_to_remove_association "Remove Reward", f, class: 'button tiny alert radius expand reward_btn' %>

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/index.html.erb
<div id="slider">
  <ul class="example-orbit" data-orbit>
  
    <% @most_recent_project.each do |latest_project| %>
    <li>
     <img src="http://lorempixel.com/900/300/technics/<%= latest_project.picture_url %>" alt="slide 2" />

     <div class="description text-center">
      <%= latest_project.description %>
     </div>

      <div class="orbit-caption">
        <em>By <%= link_to latest_project.title, project_path(latest_project)%></em>
      </div>
    </li>
    <% end %>
  </ul>

  <%= link_to "Start a Project", new_project_path, class: "button success radius large start" %>

</div><!-- #slider -->

<br>
  <div class="row">

    <div class="medium-2 columns">

      <ul class="side-nav">
         <li><strong>Category</strong></li>

        <% @categories.each do |category| %> 

          <li><%= link_to category.name, projects_path, data: {remote: true, params: { category_id: category.id }.to_param }, class: "category_link" %></li>

       
         <% end %> 

      </ul>

    </div>

    <div class="medium-10 columns">

      <ul class="breadcrumbs">
        <li><%= link_to "All Projects", projects_path %></li>
      </ul>

   <div id="money-raised-for-the-category"></div>
    <div id="effect-6" class="effects all_projects clearfix">

       <ul class="small-block-grid-3">
        <%= render @projects %>
      </ul>
    </div>
 

      <div id="paginate">
        <%= paginate @projects,:remote => true %>
      </div>

    </div>

  </div>

app/views/projects/index.js.erb
$('.all_projects').html(
	"<ul class='small-block-grid-3'><%=  j(render @projects)%></ul>")
<%if @category%>
	console.log("<%=@category.get_money_raised_for_the_category%>")
	$("#money-raised-for-the-category").html("<span class='label round'>Category: <strong><%=@category.name %></strong> - $<%=@category.get_money_raised_for_the_category%> raised</span>")
<%end%>
$('#paginate').html("<%= j( paginate(@projects, :remote => true).to_s)%>");

app/views/projects/new.html.erb
<div class="row">
	<div class = "wrapper">
	<div class="medium-6 medium-centered columns padding_div">		
<h1>Create a Project</h1>
<%= render 'form'  %>
</div> <!-- div padding_div -->
</div>

app/views/projects/show.html.erb
<div class="margin"></div>
<div class="margin"></div>

  <div class="row">


    <div class="medium-4 columns">

      <%= image_tag @project.image.url, class: "th",alt: "slide 2" %>

      <div class="row">

        <div class="medium-12 columns">

  <% @project.reviews.each do |review| %>
    <p>
      <%= review.comment %>
      <br>
      <% if review.user != nil %>
        <em> by <%= review.user.email %></em>
        Added on: <%= review.created_at %>
      <% end %>
    </p>
  <% end %>
  </div>

  <div>
  <!-- <a href="#" id="myModal_btn" class='button small round right'>New Review</a> -->

  <div id="myModal" >
  <% if current_user %>
    <%= form_for([@project, @review]) do |f| %>

    <div class="field">
      <%= f.label :leave_a_review %><br />
      <%= f.text_area :comment %>
    </div>
    <div class="actions">
      <%= f.submit "Submit Comment", :id => "review_submit", class: 'button tiny radius'%>
    </div>
    <% end %>
    
     <% else %>
    <p>Please <%= link_to "login", new_session_path %> to add a review</p>
     <% end %>

 </div>


</div>



        </div>



    </div>

    <div class="medium-8 columns">
  
      <div class="row project_title"> 

         <div class="medium-8 columns"> <h4>Title: <%= @project[:title] %></h4></div>

        <div class="medium-4 medium-pull-1 columns">
          <h4 id ="user_pledge_state" class="label secondary round" data-amount-pledged =<%= @current_user_amount_pledged%>>      
          </h4>
        </div>     

      </div> 

      <hr>

      <div class="row">

        <div class="medium-6 columns">
            <div id="el" data-attribute-el></div><br>

            <div class="progress round" data-attribute-progress>
              <span class="meter" style="width: 1%"></span>
              <span class="goal" data-attribute-goal=<%= @project.goal %>></span>
            </div>

        </div><br>

        <div class="medium-6 columns">
           <span class="button alert round fund_raised" data-attribute-amount= <%= @sum_of_amount %>>$ <%= @sum_of_amount %> Raised</span>
        </div>
        
      </div><!-- row -->
      <div class="row">
        <table class="table">
          <thead>
            <tr>
              <th width="250">Start Date: <span><%= @project.start_time.to_date  %></span></th>
              <th width="250">End Date: <span><%= @project.end_time.to_date  %></span></th>
              <th width="250">Days left: <span><%= @project.get_days_left %></span></th>
            </tr>
          </thead>
        </table>
      </div>
      <hr>   
      <ul class="pricing-table">
        <li class="price">Goal:$<%= @project.goal %></li>
        <li class="description"><em>Descriptions:</em> <%= @project[:description] %></em></li>
        <li class="bullet-item">Currently Raised: $<%= @sum_of_amount %></li>
        <li class="bullet-item">There are <span id="num_supporters" data-num-supporters=<%= @total_supporters%>><%= @total_supporters%></span> supports for this project</li>
      </ul>   

      </div>
<hr>
  </div><!-- row -->


  <div class="row">


    <div class="medium-4 columns">



            <div class="panel panel-default">
              <!-- Default panel contents -->
              <div><%= image_tag @project.user.avatar.url(:medium), size: "350x150", alt: "Test" %></div>
              <div class="panel-heading text-center"><em><%= @project.user.username %></em></div>
              <div class="panel-body">

                <p>Biography: <%= @project.user.biography %></p>
              </div>
              <div class="panel-footer">
                <ul class="inline-list author">
                  <li class="text-center"><a href="#" data-reveal-id="bio">Bio</a></li>
                  <li class="text-center"><a href="#" data-reveal-id="contact">Contact</a></li>
                </ul>

                <div id="bio" class="reveal-modal small panel callout" data-reveal>
                  <h2>Biography: <%= @project.user.username %></h2>
                  <p><%= @project.user.biography %></p>
                  <a class="close-reveal-modal">&#215;</a>
                </div>

                 <div id="contact" class="reveal-modal small panel" data-reveal>
                  <h2>Get in Touch with <%= @project.user.username %></h2>
                 

                    <form>
                    <div class="row">
                      <div class="large-12  columns">
                        <label>Name:
                          <input type="text" placeholder="Your Name" />
                        </label>
                      </div>
                    </div>

                    <div class="row">
                      <div class="large-12 columns">
                        <label>Note
                          <textarea type="text" rows="3"/></textarea>
                        </label>
                      </div>
                    </div>

                    </form>
                    <hr>

                  <div class="row">
                      <div class="large-12 columns">
                          <ul class="inline-list text-center">
                            <li><i class="fi-social-facebook large"></i></li>
                            <li><i class="fi-social-twitter large"></i></li>
                          </ul>
                      </div>
                    </div>

                  <a class="close-reveal-modal">&#215;</a>
                </div>
              </div>           
            </div><!-- panel -->
          </div>
  
    <div class="medium-8 columns">

      <div class="row">
        <div class="medium-10 medium-offset-1 columns pledge">
          <h4 class="text-center">Pledge on this Project</h4>
        </div>
      </div>

      <div class="row">

         <div class="medium-12 columns">

            <div class="row" data-equalizer>
                <% @rewards.each do |reward|%>
                  <div class="medium-4 columns end">
                    <ul class="pricing-table" data-equalizer-watch>
                      <li class="title">$<%= reward.amount %></li>
                      <li class="divider"></li>
                      <li class="description"><%=reward.description%></li>
                      <li class="count_pledges text-center" data-pledge-count= <%= reward.pledges.count %>><%= reward.pledges.count %> backers</li>
                      <% if current_user %>
                        <% if !@project.is_expired?%>
                          <li class="cta-button">
                            <%= form_tag( pledges_path,{:method=>:post, :class => 'pledge_form'}) do%>
                              <%= hidden_field_tag :user_id, current_user.id %>
                              <%= hidden_field_tag :reward_id, reward.id %>
                              <%= submit_tag "Pledge", class: "button small alert radius pledge_button"%>
                            <% end %>    
                          </li>
                        <% else %>
                          <li>The project has expired.</li>
                        <% end %>    
                      <% else %>
                      <li>please <%= link_to("Login",new_session_path) %> to pledge </li>
                      <% end %>
                    </ul>
                  </div>
                <% end %>
               
            </div>
          
        </div>

      </div>
    
  </div><!-- row -->



  <div>
    