config/routes.rb
Rails.application.routes.draw do

  root to: 'projects#index'

  resources :sessions, :only => [:destroy, :create, :new]
  
  resources :projects do #, :only =>[:new, :create, :index, :show] 
    resources :reviews, :only => [:index, :show, :create]
  end

  resources :pledges, :only =>[:create]

  resources :categories, :only =>[:index, :show]

  resources :users, :only =>[:new, :create, :show, :edit, :update]

  resources :user_sessions, :only=>[:new,:create, :destroy]
  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout


end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :projects
	
	validates :name, :presence => true

	def get_money_raised_for_the_category
		projects.inject(0){|sum, project|
			rewards = project.rewards
			rewards.each{ |reward|
				sum += reward.pledges.count * reward.amount
			}
			sum
		}
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
 before_action :set_category, only: [:show, :edit, :update, :destroy]
 before_filter :ensure_logged_in, :only => [:new, :create]



  def index
  	
  end

  def show
    @categories = Category.all  
    @category = Category.find(params[:id])
    @most_recent_project = @category.projects.most_recent_five
    @per_category = @category.projects
    @projects = @projects.order(created_at: :desc).page(params[:page])
  end

  def new
    @category = Category.new
  end

  def create
    @category.new(category_params)
    if @category.save 
      redirect_to project_path(@category.id)
    else
      render 'new'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/show.html.erb
<div id="slider">
  <ul class="example-orbit" data-orbit>
  
    <% @most_recent_project.each do |latest_project| %>
    <li>
     <img src="http://lorempixel.com/900/300/technics/<%= latest_project.picture_url %>" alt="slide 2" />

     <div class="description text-center">
      <%= latest_project.description %>
     </div>

      <div class="orbit-caption">
        <em>By <%= link_to latest_project.title, project_path(latest_project.id)%></em>
      </div>
    </li>
    <% end %>
  </ul>

  <a class="button success radius large start" href="add_project.html">Start a Project</a>

</div><!-- #slider -->

<br>
  <div class="row">


    <div class="medium-2 columns">

      <ul class="side-nav">
         <li><strong>Category</strong></li>

        <% @categories.each do |category| %> 

          <li><%= link_to category.name, category_path(category) %></li>
       
         <% end %> 

      </ul>

    </div>

    <div class="medium-10 columns">

        <ul class="breadcrumbs">
      <li><%= link_to "All Projects", projects_path %></li>
      <li>category: <%= link_to @category.name, category_path(@category) %></li>
    </ul>

      <ul class="small-block-grid-3">

        <%  @per_category.each do |project| %>
          <li><%= link_to image_tag('http://lorempixel.com/200/150/technics/' + project.picture_url), project_path(project) %></li>
       <% end %>


        </ul>

      

        </div>

      

    </div><!-- row -->