config/routes.rb
Rails.application.routes.draw do

  root to: 'projects#index'

  resources :sessions, :only => [:destroy, :create, :new]
  
  resources :projects do #, :only =>[:new, :create, :index, :show] 
    resources :reviews, :only => [:index, :show, :create]
  end

  resources :pledges, :only =>[:create]

  resources :categories, :only =>[:index, :show]

  resources :users, :only =>[:new, :create, :show, :edit, :update]

  resources :user_sessions, :only=>[:new,:create, :destroy]
  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout


end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<div class="fixed contain-to-gird">
  <nav class="top-bar" data-topbar>
    <ul class="title-area">
      <li class="name">
        <%= link_to("CrowdFounder", root_path) %>
      </li>
       <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>

    <section class="top-bar-section">
    
      <!-- Left Nav Section -->
      <ul class="left">
   

        <li class="has-form" id="search">

          <div class="row collapse">


        <%= form_tag projects_path, method: :get, authentication: false, id: 'search-form' do %>

            <div class="large-1 small-3 columns">
             <i class="fi-magnifying-glass button success search"></i>

            </div>

            <div class="large-10 small-9 columns">
             <%= text_field_tag :search, params[:search], class: 'search_input', value: 'Search Projects' %>
            </div>
             <% end %>

          </div>
        </li>

        <li class="has-form">   
           <%= link_to "Start a New Project", new_project_path, class: 'button success large radius' %>
        </li>

        
        
      </ul>

      <ul class="number_projects"> 
        <li>
          <%= link_to "Total money raised for all projectes : $#{get_total_money_raised}", "#", class: 'button large radius' %>
        </li>

      <!--   <li><p id='fully-fund-project-count' style="color:white" data-fully-fund-projects='<%=get_successfully_fund_projects.count%>'></p></li> -->
      </ul>

      <!-- Right Nav Section -->
      <ul class="right userinfo">

         <% if current_user %>
            <li><%= link_to "Hi! #{current_user.email}", user_path(current_user) %></li>

            <li><%= link_to "Log out", session_path("current"), :method => :delete %> </li> 

          <% else %>
         <li><%= link_to "Log in", new_session_path %></li>
         <li> <%= link_to "Sign up", new_user_path %></li>

         <% end %>
      </ul>
    </section>
  </nav>
</div><!-- fixed navbar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Crowdfunder" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Crowdfunder" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container"> 
      <%= render 'layouts/navigation' %>
      <%= yield %>
    </div><!-- container -->
  </body>
</html>